# -*- coding: utf-8 -*-
"""Perfil_Demanda_Electrico_Comunidad_Poisson_v1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYMKK8MOQIFzETNawWQ0SDgsHQ4VRWOW
"""

# ============================================================
# GOOGLE COLAB / PYTHON
# Stochastic hourly household electric demand profile (8760 h)
# for 1 dwelling and aggregation to N dwellings using Poisson
#
# Includes:
# - Lighting (4 LED bulbs of 10 W)
#   * 2 bulbs fixed during night hours
#   * 2 bulbs stochastic during morning/evening activity
# - Refrigerator (300 W) with cycling behavior
# - Mini-split
# - Television
# - Blender
# - Microwave
# - Washing machine
#
# Outputs:
# - Annual hourly demand profile
# - CSV files for TRNSYS
# - Plots
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dataclasses import dataclass, field
from typing import Dict, List, Optional

# -----------------------------
# 1) USER SETTINGS
# -----------------------------
YEAR = 2025              # Use a non-leap year to ensure 8760 hours
N_HOUSES = 50            # Number of households
RANDOM_SEED = 42         # Reproducibility
EXPORT_PREFIX = "stochastic_household_load"

# -----------------------------
# 2) TIME INDEX (8760 h)
# -----------------------------
time_index = pd.date_range(
    start=f"{YEAR}-01-01 00:00:00",
    end=f"{YEAR}-12-31 23:00:00",
    freq="H"
)

assert len(time_index) == 8760, "Selected year does not contain 8760 hours."

calendar_df = pd.DataFrame(index=time_index)
calendar_df["month"] = calendar_df.index.month
calendar_df["day"] = calendar_df.index.day
calendar_df["hour"] = calendar_df.index.hour
calendar_df["dayofweek"] = calendar_df.index.dayofweek  # Monday=0, Sunday=6
calendar_df["is_weekend"] = calendar_df["dayofweek"] >= 5
calendar_df["date"] = calendar_df.index.date

unique_days = pd.Index(sorted(calendar_df["date"].unique()))

# -----------------------------
# 3) APPLIANCE MODEL
# -----------------------------
@dataclass
class Appliance:
    name: str
    power_W: float
    mode: str  # "always_on", "fixed_schedule", "hour_slots", "events", "cycling"

    # Daily usage
    daily_usage_h: Optional[float] = None
    daily_usage_range_h: Optional[tuple] = None

    # Event duration
    event_duration_h: Optional[float] = None

    # Hour weights (24 values)
    hour_weights: List[float] = field(default_factory=lambda: [1.0] * 24)

    # Event start-hour weights (24 values)
    start_hour_weights: Optional[List[float]] = None

    # Fixed schedule (24 values of 0/1 or fractional use)
    fixed_hour_schedule: Optional[List[float]] = None

    # Weekday/weekend modifiers
    weekday_factor: float = 1.0
    weekend_factor: float = 1.0

    # Monthly modifiers
    month_factors: Dict[int, float] = field(default_factory=lambda: {m: 1.0 for m in range(1, 13)})

    # Limit active hours/day
    max_daily_hours: Optional[float] = None

    # Cycling loads (e.g., refrigerator)
    base_duty_cycle: Optional[float] = None


# -----------------------------
# 4) HELPER FUNCTIONS
# -----------------------------
def normalize_weights(w):
    w = np.array(w, dtype=float)
    w[w < 0] = 0.0
    s = w.sum()
    if s <= 0:
        w = np.ones_like(w, dtype=float)
        s = w.sum()
    return w / s


def sample_unique_hours(k, weights, rng):
    """
    Sample k unique hours from 0..23 according to weighted probabilities.
    """
    weights = normalize_weights(weights)
    hours = np.arange(24)

    positive_mask = weights > 0
    positive_hours = hours[positive_mask]
    positive_weights = weights[positive_mask]

    if len(positive_hours) == 0 or k <= 0:
        return np.array([], dtype=int)

    k = min(int(k), len(positive_hours))
    positive_weights = positive_weights / positive_weights.sum()

    return np.sort(rng.choice(positive_hours, size=k, replace=False, p=positive_weights))


def sample_event_start_hours(n_events, weights, rng):
    """
    Sample event start hours with replacement.
    """
    weights = normalize_weights(weights)
    hours = np.arange(24)

    if n_events <= 0:
        return np.array([], dtype=int)

    return rng.choice(hours, size=int(n_events), replace=True, p=weights)


def add_event_block(day_profile_W, start_hour, duration_h, power_W):
    """
    Add an event block to the daily hourly profile.
    Supports fractional duration.
    """
    remaining = duration_h
    h = int(start_hour)

    while remaining > 1e-9 and h < 24:
        frac = min(1.0, remaining)
        day_profile_W[h] += power_W * frac
        remaining -= frac
        h += 1


def get_day_factor(is_weekend, appliance):
    return appliance.weekend_factor if is_weekend else appliance.weekday_factor


def get_month_factor(month, appliance):
    return appliance.month_factors.get(month, 1.0)


def simulate_one_household_profile(appliances, calendar_df, unique_days, rng):
    """
    Simulate one household over the full year.
    Returns an hourly power profile in W (length 8760).
    """
    profile_W = np.zeros(len(calendar_df), dtype=float)
    date_to_idx = calendar_df.groupby("date").indices

    for day in unique_days:
        day_idx = date_to_idx[day]
        day_slice = calendar_df.iloc[day_idx]

        month = int(day_slice["month"].iloc[0])
        is_weekend = bool(day_slice["is_weekend"].iloc[0])

        day_profile_W = np.zeros(24, dtype=float)

        for ap in appliances:
            day_factor = get_day_factor(is_weekend, ap)
            month_factor = get_month_factor(month, ap)

            # -----------------------------------
            # ALWAYS ON
            # -----------------------------------
            if ap.mode == "always_on":
                if ap.daily_usage_h is None:
                    raise ValueError(f"{ap.name}: daily_usage_h is required for mode='always_on'")
                duty = min(ap.daily_usage_h / 24.0, 1.0)
                day_profile_W += ap.power_W * duty * day_factor * month_factor

            # -----------------------------------
            # FIXED SCHEDULE
            # -----------------------------------
            elif ap.mode == "fixed_schedule":
                if ap.fixed_hour_schedule is None:
                    raise ValueError(f"{ap.name}: fixed_hour_schedule is required for mode='fixed_schedule'")

                schedule = np.array(ap.fixed_hour_schedule, dtype=float)
                if len(schedule) != 24:
                    raise ValueError(f"{ap.name}: fixed_hour_schedule must contain 24 values")

                multiplier = day_factor * month_factor
                day_profile_W += ap.power_W * schedule * multiplier

            # -----------------------------------
            # HOUR SLOTS
            # -----------------------------------
            elif ap.mode == "hour_slots":
                if ap.daily_usage_range_h is not None:
                    base_mean_h = rng.uniform(ap.daily_usage_range_h[0], ap.daily_usage_range_h[1])
                elif ap.daily_usage_h is not None:
                    base_mean_h = ap.daily_usage_h
                else:
                    raise ValueError(f"{ap.name}: daily_usage_h or daily_usage_range_h required for mode='hour_slots'")

                mean_h = base_mean_h * day_factor * month_factor

                if ap.max_daily_hours is not None:
                    mean_h = min(mean_h, ap.max_daily_hours)

                active_hours = rng.poisson(lam=max(mean_h, 0.0))
                active_hours = min(active_hours, 24)

                chosen_hours = sample_unique_hours(active_hours, ap.hour_weights, rng)
                day_profile_W[chosen_hours] += ap.power_W

            # -----------------------------------
            # EVENTS
            # -----------------------------------
            elif ap.mode == "events":
                if ap.daily_usage_h is None:
                    raise ValueError(f"{ap.name}: daily_usage_h is required for mode='events'")
                if ap.event_duration_h is None:
                    raise ValueError(f"{ap.name}: event_duration_h is required for mode='events'")

                mean_daily_usage_h = ap.daily_usage_h * day_factor * month_factor
                duration_h = ap.event_duration_h

                mean_events = max(mean_daily_usage_h / duration_h, 0.0)
                n_events = rng.poisson(lam=mean_events)

                start_weights = ap.start_hour_weights if ap.start_hour_weights is not None else ap.hour_weights
                start_hours = sample_event_start_hours(n_events, start_weights, rng)

                for sh in start_hours:
                    add_event_block(day_profile_W, int(sh), duration_h, ap.power_W)

            # -----------------------------------
            # CYCLING LOADS
            # -----------------------------------
            elif ap.mode == "cycling":
                if ap.base_duty_cycle is None:
                    raise ValueError(f"{ap.name}: base_duty_cycle is required for mode='cycling'")

                hour_weights = np.array(ap.hour_weights, dtype=float)
                hour_weights = hour_weights / np.mean(hour_weights)  # normalize around 1.0

                for h in range(24):
                    duty_h = ap.base_duty_cycle * hour_weights[h] * day_factor * month_factor

                    # Add small stochastic variation
                    duty_h *= rng.uniform(0.90, 1.10)

                    # Physical limits
                    duty_h = np.clip(duty_h, 0.05, 0.95)

                    day_profile_W[h] += ap.power_W * duty_h

            else:
                raise ValueError(f"Unknown appliance mode: {ap.mode}")

        profile_W[day_idx] = day_profile_W

    return profile_W


# -----------------------------
# 5) APPLIANCE DEFINITIONS
# -----------------------------

# Lighting:
# 4 bulbs x 10 W
# - Base lighting: 2 bulbs = 20 W, active at night
# - Additional lighting: 2 bulbs = 20 W, stochastic use

# Base night lighting schedule:
# 00:00-06:00 ON, 19:00-23:00 ON
base_light_schedule = [
    1, 1, 1, 1, 1, 1,   # 00-05
    1, 0, 0, 0, 0, 0,   # 06-11
    0, 0, 0, 0, 0, 0,   # 12-17
    0, 1, 1, 1, 1, 1    # 18-23
]

# Additional lighting weights (morning and especially evening)
additional_light_hour_weights = [
    0.02, 0.01, 0.01, 0.01, 0.01, 0.03,
    0.18, 0.12, 0.03, 0.01, 0.01, 0.01,
    0.01, 0.01, 0.01, 0.02, 0.03, 0.08,
    0.40, 0.85, 1.00, 0.95, 0.75, 0.30
]

# Refrigerator hourly weighting: more activity in hot daytime hours
fridge_hour_weights = [
    0.90, 0.88, 0.86, 0.85, 0.85, 0.88,
    0.95, 1.00, 1.05, 1.10, 1.15, 1.20,
    1.25, 1.28, 1.30, 1.30, 1.25, 1.20,
    1.15, 1.10, 1.05, 1.00, 0.95, 0.92
]

# Mini-split hourly weights
minisplit_hour_weights = [
    0.10, 0.10, 0.08, 0.08, 0.08, 0.10,
    0.15, 0.20, 0.30, 0.45, 0.60, 0.80,
    1.00, 1.00, 1.00, 1.00, 0.95, 0.90,
    0.85, 0.80, 0.70, 0.55, 0.35, 0.20
]

# TV weights
tv_hour_weights = [
    0.02, 0.01, 0.01, 0.01, 0.01, 0.02,
    0.05, 0.08, 0.06, 0.04, 0.04, 0.05,
    0.06, 0.05, 0.05, 0.06, 0.08, 0.15,
    0.45, 0.75, 1.00, 0.95, 0.70, 0.30
]

# Blender event start weights
blender_start_weights = [
    0.00, 0.00, 0.00, 0.00, 0.00, 0.02,
    0.30, 0.55, 0.40, 0.08, 0.03, 0.05,
    0.18, 0.35, 0.18, 0.05, 0.02, 0.06,
    0.18, 0.30, 0.20, 0.04, 0.01, 0.00
]

# Microwave event start weights
microwave_start_weights = [
    0.00, 0.00, 0.00, 0.00, 0.00, 0.01,
    0.18, 0.40, 0.25, 0.08, 0.04, 0.08,
    0.20, 0.42, 0.22, 0.08, 0.05, 0.08,
    0.22, 0.45, 0.28, 0.08, 0.02, 0.00
]

# Washing machine weights
washer_start_weights = [
    0.00, 0.00, 0.00, 0.00, 0.00, 0.00,
    0.02, 0.04, 0.08, 0.20, 0.35, 0.50,
    0.55, 0.55, 0.50, 0.42, 0.35, 0.25,
    0.12, 0.05, 0.02, 0.00, 0.00, 0.00
]

# Mini-split month factors
minisplit_month_factors = {
    1: 0.55, 2: 0.55, 3: 0.70, 4: 0.90,
    5: 1.10, 6: 1.20, 7: 1.25, 8: 1.25,
    9: 1.10, 10: 0.85, 11: 0.65, 12: 0.55
}

# Refrigerator month factors
fridge_month_factors = {
    1: 0.95, 2: 0.95, 3: 0.98, 4: 1.00,
    5: 1.05, 6: 1.10, 7: 1.15, 8: 1.15,
    9: 1.10, 10: 1.03, 11: 0.98, 12: 0.95
}

appliances = [
    Appliance(
        name="Base lighting (2 x 10 W)",
        power_W=20,
        mode="fixed_schedule",
        fixed_hour_schedule=base_light_schedule,
        weekday_factor=1.00,
        weekend_factor=1.00
    ),
    Appliance(
        name="Additional lighting (2 x 10 W)",
        power_W=20,
        mode="hour_slots",
        daily_usage_h=4.0,
        hour_weights=additional_light_hour_weights,
        weekday_factor=1.00,
        weekend_factor=1.15,
        max_daily_hours=8
    ),
    Appliance(
        name="Refrigerator",
        power_W=300,
        mode="cycling",
        base_duty_cycle=0.35,
        hour_weights=fridge_hour_weights,
        weekday_factor=1.00,
        weekend_factor=1.02,
        month_factors=fridge_month_factors
    ),
    Appliance(
        name="Mini-split 1 TR",
        power_W=0,
        mode="hour_slots",
        daily_usage_range_h=(9, 14),
        hour_weights=minisplit_hour_weights,
        weekday_factor=1.00,
        weekend_factor=1.05,
        month_factors=minisplit_month_factors,
        max_daily_hours=24
    ),
    Appliance(
        name="Television",
        power_W=30,
        mode="hour_slots",
        daily_usage_h=4.0,
        hour_weights=tv_hour_weights,
        weekday_factor=1.00,
        weekend_factor=1.20,
        max_daily_hours=12
    ),
    Appliance(
        name="Blender",
        power_W=1000,
        mode="events",
        daily_usage_h=0.1,
        event_duration_h=0.1,
        start_hour_weights=blender_start_weights,
        weekday_factor=1.00,
        weekend_factor=1.10
    ),
    Appliance(
        name="Microwave",
        power_W=1050,
        mode="events",
        daily_usage_h=0.1,
        event_duration_h=0.1,
        start_hour_weights=microwave_start_weights,
        weekday_factor=1.00,
        weekend_factor=1.05
    ),
    Appliance(
        name="Washing machine",
        power_W=880,
        mode="events",
        daily_usage_h=2.0,
        event_duration_h=2.0,
        start_hour_weights=washer_start_weights,
        weekday_factor=0.85,
        weekend_factor=1.35
    )
]

# -----------------------------
# 6) SIMULATE N HOUSEHOLDS
# -----------------------------
all_profiles = np.zeros((N_HOUSES, len(calendar_df)), dtype=float)

for i in range(N_HOUSES):
    house_rng = np.random.default_rng(RANDOM_SEED + i + 1)
    all_profiles[i, :] = simulate_one_household_profile(appliances, calendar_df, unique_days, house_rng)

aggregate_profile_W = all_profiles.sum(axis=0)
average_profile_per_house_W = aggregate_profile_W / N_HOUSES

# -----------------------------
# 7) BUILD OUTPUT DATAFRAME
# -----------------------------
results = pd.DataFrame({
    "datetime": calendar_df.index,
    "month": calendar_df["month"].values,
    "day": calendar_df["day"].values,
    "hour": calendar_df["hour"].values,
    "dayofweek": calendar_df["dayofweek"].values,
    "is_weekend": calendar_df["is_weekend"].astype(int).values,
    "load_total_W": aggregate_profile_W,
    "load_avg_per_house_W": average_profile_per_house_W
})

# Hour count from start of year
results["time_h_from_start"] = np.arange(len(results), dtype=float)

# -----------------------------
# 8) EXPORT CSV FILES
# -----------------------------
full_csv = f"{EXPORT_PREFIX}_full_results.csv"
trnsys_total_csv = f"{EXPORT_PREFIX}_TRNSYS_total_load.csv"
trnsys_avg_csv = f"{EXPORT_PREFIX}_TRNSYS_avg_per_house.csv"

results.to_csv(full_csv, index=False)
results[["time_h_from_start", "load_total_W"]].to_csv(trnsys_total_csv, index=False)
results[["time_h_from_start", "load_avg_per_house_W"]].to_csv(trnsys_avg_csv, index=False)

print("Files exported:")
print(f" - {full_csv}")
print(f" - {trnsys_total_csv}")
print(f" - {trnsys_avg_csv}")

# -----------------------------
# 9) SUMMARY STATISTICS
# -----------------------------
peak_W = results["load_total_W"].max()
mean_W = results["load_total_W"].mean()
annual_energy_kWh = results["load_total_W"].sum() / 1000.0  # hourly sum in Wh -> kWh

print("\nSummary:")
print(f"Number of houses simulated: {N_HOUSES}")
print(f"Peak total demand: {peak_W:,.2f} W")
print(f"Average total demand: {mean_W:,.2f} W")
print(f"Annual total energy: {annual_energy_kWh:,.2f} kWh")

# -----------------------------
# 10) PLOTS
# -----------------------------

# Full year
plt.figure(figsize=(16, 5))
plt.plot(results["datetime"], results["load_total_W"], linewidth=0.6)
plt.title(f"Annual hourly electric demand profile - {N_HOUSES} households")
plt.xlabel("Date")
plt.ylabel("Demand (W)")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# First week
mask_first_week = results["datetime"] < (results["datetime"].iloc[0] + pd.Timedelta(days=7))

plt.figure(figsize=(16, 5))
plt.plot(
    results.loc[mask_first_week, "datetime"],
    results.loc[mask_first_week, "load_total_W"],
    marker="o",
    linewidth=1.0
)
plt.title(f"First week hourly profile - {N_HOUSES} households")
plt.xlabel("Date")
plt.ylabel("Demand (W)")
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Mean daily profile
hourly_mean = results.groupby("hour")["load_total_W"].mean()

plt.figure(figsize=(10, 5))
plt.plot(hourly_mean.index, hourly_mean.values, marker="o")
plt.title(f"Mean hourly demand profile by hour of day - {N_HOUSES} households")
plt.xlabel("Hour of day")
plt.ylabel("Mean demand (W)")
plt.xticks(range(24))
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()